import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Manrope } from "next/font/google";
import SideBar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const manrope = Manrope({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${manrope.className} ${geistSans.variable} ${geistMono.variable} antialiased `}
      >
        <div className="flex h-screen ">
          <Navbar />
          <SideBar />
          {/* <div className="min-h-screen pt-10   bg-white text-black flex"> */}
          {/* <div className="fixed top-10 min-w-[80px] max-w-[250px] h-screen flex-shrink-0"> */}
          {/* </div> */}
          <div className="sidebar-expanded:px-6 sidebar-expanded:ml-80 ml-20 mt-16 p-8 transition-all relative flex flex-col flex-1 lg:overflow-y-auto lg:overflow-x-hidden">
            {children}
          </div>
          {/* </div> */}
        </div>
      </body>
    </html>
  );
}
